version: '3.7'
    
services:
  cadvisor:
    image: google/cadvisor:v0.33.0
    hostname: "{{.Node.Hostname}}"
    command: -logtostderr -docker_only
    volumes:
      # 設定 volumes，由於需要監控 container，
      # 因此需要給予 docker.sock 權限
      # :ro -> read only，不用擔心 docker 被改寫
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      # global，顧名思義，全部機器都會部屬
      mode: global
      resources:
        # 限制使用的資源，不用擔心監控會很耗資源，
        # 最多只要 128 MB 而已
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - my_network

networks:
  my_network:
    external: true