version: '3.8'

services:
  grafana:
    image: linsamtw/class01_grafana:6.3
    ports:
      - target: 3000
        published: 3000
        mode: host
    user: root
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints: [node.labels.grafana == true]
    restart: always
    networks:
        - my_network

networks:
  my_network:
    # 加入已經存在的網路
    external: true