{
 "title": "機器狀態",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "netdata_system_cpu_percentage_average{dimension=\"user\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Free Memory (MB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (netdata_system_ram_MiB_average{dimension=~\"cached|free\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "System Process Running",
   "type": "graph",
   "description": "System processes. **Running** are the processes in the CPU. **Blocked** are processes that are willing to enter the CPU, but they cannot, e.g. because they wait for disk activity.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "processes" }
   ],
   "targets": [
    {
     "expr": "netdata_system_processes_processes_average{dimension=\"running\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "System Process Blocked",
   "type": "graph",
   "description": "System processes. **Running** are the processes in the CPU. **Blocked** are processes that are willing to enter the CPU, but they cannot, e.g. because they wait for disk activity.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "processes" }
   ],
   "targets": [
    {
     "expr": "netdata_system_processes_processes_average{dimension=\"blocked\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "System Active Processes",
   "type": "graph",
   "description": "All system processes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "processes" }
   ],
   "targets": [
    {
     "expr": "netdata_system_active_processes_processes_average",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Free Disk Space (GB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (netdata_disk_space_GiB_average{dimension=\"avail\"})",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}