version: '3.8'
services:
  crawler_scheduler:
    # 設定 image
    image: linsamtw/class01_crawler:dev
    # 設定 hostname, 用於 flower 上顯示
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}"
    # 啟動 worker 指令
    command: pipenv run python financialdata/scheduler.py
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        max_replicas_per_node: 1
        constraints: [node.labels.crawler_scheduler == true]
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
        - my_network

networks:
  my_network:
    # 加入已經存在的網路
    external: true
